spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/customers_database
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  activemq:
    pool:
      max-connections: 10
server:
  port: 8443